### ISSUE TITLE
Thanks for supporting h265.  Can we support setting the cache time next?

### ISSUE THREAD

**Issue by pengxiao18** [alexeyvasilyev/rtsp-client-android#85]

**Comment by pengxiao18** [comment]
What I mean is that the function of increasing the settable audio and video buffering storage time will help playback stability

**Comment by pengxiao18** [comment]
There is no audio and video cache, and there will be occasional freezes during playback.

**Comment by alexeyvasilyev** [comment]
This is by design at the moment. Video frames sent as soon as possible to decoder when it is arrived.
Audio does not have such issue since buffering is done on Android (audio should be smooth).

If you need smooth video playback, use ExoPlayer. It supports RTSP. It has a buffer for a couple sec. But you will have a couple sec delay.
