### ISSUE TITLE
Sometimes the rtsp connection fails

### ISSUE THREAD

**Issue by shervinkoushan** [alexeyvasilyev/rtsp-client-android#98]
![image](https://github.com/user-attachments/assets/605be3bc-16d0-425c-9dfb-aec1f261aee0)

In these cases, it does not work again until I restart the camera. Any idea what the issue could be?

**Comment by alexeyvasilyev** [comment]
Looks like camera end issue.

The HTTP status code 503 means that the server is currently unable to handle the incoming requests. Usually, this error occurs because the server is too busy or is temporarily down for maintenance. The backend server is overloaded or beyond its capacity and cannot handle any new incoming client requests.
